### ISSUE TITLE
怎么加入更多的数据呢

### ISSUE THREAD

**Issue by uaucnets** [TingGe/data-visualization#3]
怎么去随时插入更多的数据呢，在攻击地图上，ipviking

**Comment by TingGe** [comment]
@uaucnets 不太清楚你要修改配置数据还是攻击的实时数据。我都说下好了，如果没描述清楚可以继续聊：

ipviking 是 [Norse](http://www.norse-corp.com/) 之前的一个案例。我只是逆向折腾了下。

- 配置数据，存放在[`ipviking/data`](https://github.com/TingGe/data-visualization/tree/master/ipviking/data)目录，可以编辑对应的文件。
- 实时数据，使用的 Norse 的一个 websocket 服务实时更新数据（现在好像停止服务了）；可以自己配个 websocket 的 Mock 来随机时间地响应数据就能看效果了。ws 配置在 [`ipviking/scripts/ipviking.js`](https://github.com/TingGe/data-visualization/blob/master/ipviking/scripts/ipviking.js) 中 66 ～70 行。

 websocket 服务 Mock 的数据结构：

```json
{
"latitude": "30.58",                        //源纬度
"longitude": "114.27",                      //源经度 
"countrycode": "CN",                        //源国家地区编码，参见 country-codes.csv
"country": "CN",                            //源国家，参见 country-codes.csv
"city": "Wuhan",                            //源城市
"org": "CHINANET HUBEI PROVINCE NETWORK",   //源组织
"latitude2": "38.62",                       //目标纬度
"longitude2": "-90.35",                     //目标经度
"countrycode2": "US",                       //目标国家地区编码，参见 country-codes.csv
"country2": "US",                           //目标国家，参见 country-codes.csv
"city2": "Saint Louis",                     //目标城市
"type": "ipviking.honey",                   //仅标识地图类型，参见 [HoneyMap]("http://map.honeynet.org/")
"md5": "221.235.189.244",                   //源IP地址
"dport": "22",                              //攻击的端口，参见port-names.tsv
"svc": "ssh",                               //攻击类型（服务）名称，参见port-names.tsv
"zerg": "rush"                              //？
}
```
值得注意的一点， [`ipviking/scripts/ipviking.js`](https://github.com/TingGe/data-visualization/blob/master/ipviking/scripts/ipviking.js) 中第 5 行有 “限制可被引用的域名”。需根据你的应用场景修改。

最后，如果你是追求技术的玩儿家，可以个折腾下 ipviking.js。如果只是要类似效果，看下网上有人写过的这篇《[前端模块化开发demo之攻击地图](http://huilan.me/blog/2015/12/05/attack-map-with-amd)》，它采用了 ECharts 实现。个人感觉还是不错的，可以试试。

**Comment by sikongsima** [comment]
收到，非常感谢，目前已经实现了想要的效果，数据可视化这一块刚接触，不是很熟，希望以后能够多多交流！
